FORMAT: 1A
HOST: https://msm-api.herokuapp.com/

# msm-api

API for weather data from JMA MSM

## Point data [/data/{ref_time}/{ft}/{level}/{element}/{lat}/{lon}]

### GET [GET]

+ Parameters 
    + ref_time: current (string) - data reference time
        + `current` the latest data
        + `yyyymmddhh`
    + ft: 0 (number) - forecast time in hours
    + level: surface - level
        + `surface`
        + `1000`
    + element: TMP (string) - physical quantity abbrev
    + lat: 35.01 (number) - latitude
    + lon: 135.77 (number) - longitude

+ Response 200 (application/json)

        {
            "ref_time": "2016081415",
            "ft": 0,
            "level": "surface",
            "element": "TMP",
            "value": 295.9
        }

## Sounding data [/sounding/{ref_time}/{ft}/{lat}/{lon}]

### GET [GET]

+ Parameters 
    + ref_time: current (string) - data reference time
        + `current` the latest data
        + `yyyymmddhh`
    + ft: 0 (number) - forecast time in hours
    + lat: 35.01 (number) - latitude
    + lon: 135.77 (number) - longitude
    
+ Response 200 (application/json)
    + Elements
        + surface    `TMP` `RH` `wind` `PRES`
        + 1000 - 300 `TMP` `RH` `wind` `HGT`
        + 250 - 100  `TMP` `wind` `HGT`

    + Body

            {
                "ref_time": "2016081415",
                "ft": 0,
                "levels": {
                    "surface": {
                        "TMP": 295.9,
                        "RH": 72.3,
                        "UGRD": 1.1,
                        "VGRD": 0.2,
                        "PRES": 1013.01
                    },
                    "1000": {
                        "TMP": 290.2,
                        "RH": 72.3,
                        "UGRD": 10.1,
                        "VGRD": 2.2,
                        "HGT": 111
                    },
                    "100": {
                        "TMP": 200.2,
                        "UGRD": 20.1,
                        "VGRD": 10.2,
                        "HGT": 16180
                    }
                }
            }


## Sky data [/sky/{ref_time}/{lat}/{lon}]

### GET [GET]

+ Parameters 
    + ref_time: current (string) - data reference time
        + `current` the latest data
        + `yyyymmddhh`
    + lat: 35.01 (number) - latitude
    + lon: 135.77 (number) - longitude
    
+ Response 200 (application/json)
    + Elements
        + upper_wind `975` `950` `925` `900` `850` each 3h
        + surface `wind` `TMP` `PRES` `APCP` `LCDC` `MCDC` `HCDC` each 1h

    + Units
        + wind 
            - from 272 `deg`
            - speed 2.1 `m/s`
        + temp 15.2 `℃`
        + rain 0.3 `mm/h`
        + presure 1013 `hPa`
        + clouds 73 `%`
            - low
            - middle
            - high
        
        
    + Body

            {
                "ref_time": "2016081415",
                "upper_wind": [
                    {
                        "ft": 0,
                        "850": { "from": 230, "speed": 9.2 },
                        "975": { "from": 273, "speed": 2.0 }
                    }
                ],
                "surface": [
                    {
                        "ft": 1,
                        "wind": { "from": 0, "speed": 0.1 }
                        "temp": 15.2,
                        "rain": 0.3,
                        "pressure": 1003
                        "clouds": { "low": 0, "middle": 30, "high": 70 }
                    }
                ]
            }